/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eprotea_icrengine_UVChecker */

#ifndef _Included_com_eprotea_icrengine_UVChecker
#define _Included_com_eprotea_icrengine_UVChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eprotea_icrengine_UVChecker
 * Method:    checkValid
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eprotea_icrengine_UVChecker_checkValid
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
